name: final_project_ba_char
description: final project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  provider: ^6.1.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  font_awesome_flutter: ^10.6.0
  lottie: ^2.7.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  
  custom_data_table:
    git: https://bitbucket.org/EliasAlfaro/custom_data_table
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/lotties/
    - assets/wallpapers/

